### ISSUE TITLE
Please read me. Whya not working or How does it work?

### ISSUE THREAD

**Issue by vkornilyev1988** [maharmstone/smbfs#1]
Hi. I like your project. But I can't compile it. Do I understand correctly that this is smbfs, which connects a remote shared folder as an ntfs disk?
I compiled the sys file, but how to work with it. Now this is very important to me. Tell me, should there be a utility to work with this method of connecting Samba? And how does this even work? I need to present it as a samba disk as an ntfs disk to hide the fact that it is a network disk. For launchers such as Battlenet. Therefore, I really hope that you will answer my questions. My os Windows 10/11 .Thank you

**Comment by maharmstone** [comment]
This project is just something I was messing about with at one time. It's not what you want.
